AllCops:
  Excludes:
    - benchmark/**/*
 
StringLiterals:
  EnforcedStyle: double_quotes
SignalException:
  Enabled: false
CollectionMethods:
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select