name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop

      - name: RSpec
        run: bundle exec rspec

  publish:
    if: contains(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: discourse/publish-rubygems-action@main
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
