name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.4
          - 2.5
          - 2.6

    steps:
      - uses: actions/checkout@v1

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Setup bundler
        run: gem install bundler

      - name: Setup gems
        run: bundle install

      - name: Rubocop
        run: bundle exec rubocop

      - name: RSpec
        run: bundle exec rspec

  publish:
    if: contains(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@5dfdb61
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
